### ISSUE TITLE
Memory Pre-Allocation

### ISSUE THREAD

**Issue by CarlosDavey** [CarlosDavey/thesis-JUCE-repo#3]
Each optimisation is probably worth its own issue, but we can use this for spit-balling a few ideas.

## 2

> Memory pre-allocation: I'm not sure this is relevant like it was in the the AP project as new springs are not dynamically instantiated but if it is possible its probably worth doing!
You allocate here

https://github.com/CarlosDavey/thesis-JUCE-repo/blob/860499801f65fe30d343d40434680ca14b959126/BasicSpringPlugin/Source/BasicSpringModal.cpp#L43-L48

here

https://github.com/CarlosDavey/thesis-JUCE-repo/blob/860499801f65fe30d343d40434680ca14b959126/BasicSpringPlugin/Source/BasicSpringModal.cpp#L67-L68

and here

https://github.com/CarlosDavey/thesis-JUCE-repo/blob/860499801f65fe30d343d40434680ca14b959126/BasicSpringPlugin/Source/BasicSpringModal.cpp#L117

If `OM_N` had some maximum, you could just set these all to a static size when the object is created. So no need for the `new`

just something like

```cpp
private:
  float OM[maxOmN]; 
  float PHI_I[maxOmN];
  float PHI_O[maxOmN];
  float C[maxOmN];
```
Also, in its current form you will leak memory as `prepareToPlay` is called every time playback starts. e.g. if someone presses pause, then play, all that stuff will happen again.

## 1

If you are using the default values, no need to copy, just have a pointer like

```cpp

private:
    float* currentOm
```

then in your constructor

```cpp
    currentOm = ((useDefaultOm) ? defaultOm : this->OM);
```

You can also start using a couple of flags to avoid duplicating calculations

```cpp
bool haveAnyParametersChanged = false;
bool haveCoefficientsBeenCalculated = false;
```

```cpp
if(haveAnyParametersChanged || !haveCoefficientsBeenCalculated)
{
    setupEverything();
    haveCoefficientsBeenCalculated = true;
}
```

If a parameter is not the same as it was the last time you checked your `haveAnyParametersChanged` should be `true` and flip to `false` when necessary.

# 3

> once I build up more it might be worth looking at doing some kind of interpolation between the omega sets to allow for smooth transitions between the sets? 

Yeah, that seems like an absolutely sensible thing to do. You would need a different dimension for each parameter, but you could certainly experiment with just a single look-up table.

You'd want to make sure the number of modes were constant of course.

_Originally posted by @mhamilt in https://github.com/CarlosDavey/thesis-JUCE-repo/issues/2#issuecomment-847994577_

**Comment by CarlosDavey** [comment]
After setting the static size, do the arrays still need to be given a specific size?

**Comment by CarlosDavey** [comment]
Also where should it be performed if not in the prepare to play?

**Comment by mhamilt** [comment]
> After setting the static size, do the arrays still need to be given a specific size?

You will still need a `size` variable for whatever data you are putting in the block of memory. All you need to do is make sure that size isn't over the maximum.

> Also where should it be performed if not in the prepare to play?

You can do a little in the constructor and you can also do things like this for dynamic memory:

```cpp
void prepareToPlay
{
  if(!memoryAllocated) // skip over this if memory is already allocated
  {
    // create new memory
  }

}
```

For your static memory approach, you won't need to worry so much.

The problem isn't allocated or altering memory in prepare to play, problem is doing it over and over again which use unnecessary processing power and potential leak if you don't `delete[]`

**Comment by CarlosDavey** [comment]
Attempting the memory pre-allocation however I am getting problems here:

https://github.com/CarlosDavey/thesis-JUCE-repo/blob/1d11b176ce571f16cdfef9fb53fd2ba4267779ac/BasicSpringPlugin/Source/BasicSpringModal.cpp#L127-L132

Any idea why I cant do this? I get an "expression must be a modifiable lvalue" error...

**Comment by mhamilt** [comment]
There is a smidgen extra faff required.

As you are statically allocating memory, you can't change the pointer to that memory. SO, you will need two sets of variables

1. The actual buckets of memory
2. pointers to that memory

**e.g.**

```cpp
float p0Mem [100] = {0};
float p1Mem [100] = {0};
float p2Mem [100] = {0};

float* p0 = p0Mem;
float* p1 = p1Mem;
float* p2 = p2Mem;

// No we can do the usual dance 

float* dummyPtr = p2;   
p2 = p1;  
p1 = p0;  
p0 = dummyPtr; 
```

**Comment by CarlosDavey** [comment]
Ah that makes sense! Okay great thanks!
