### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by CarlosDavey** [CarlosDavey/thesis-JUCE-repo#4]
So I have a basic interpolation working between frequencies, however its only really usable at each value... The spaces between don't sound great. Need to find out if this is inherent to changing the frequencies (i.e. it only sounds good at the exact calculated frequencies) or if the interpolation isnt working properly...

**Comment by mhamilt** [comment]
It wouldn't hurt to rig up something to A / B against. you'll need 

- [ ] a second instance of your spring reverb
- [ ] An `AudioParameterBool` for easy toggling
- [ ] a function that cross fades between the two reverbs on toggle change `AudioParameterBool`
